(push #p"/home/jm/Lib/Lisp/SIFT/closer-mop/" asdf:*central-registry*)
(push #p"/home/jm/Lib/Lisp/nst/" asdf:*central-registry*)
(push #p"/home/jm/Lib/Lisp/nst/test/" asdf:*central-registry*)
(push #p"/home/jm/Lib/Lisp/nst/test/asdf/" asdf:*central-registry*)
(push #p"/home/jm/Lib/Lisp/nst/test/direct/" asdf:*central-registry*)
(push #p"/home/jm/Lib/Lisp/nst/test/manual/" asdf:*central-registry*)
(push #p"/home/jm/Lib/Lisp/nst/test/meta/" asdf:*central-registry*)
(push #p"/home/jm/Lib/Lisp/nst/test/util/" asdf:*central-registry*)
